Pin optimism to 0.11.1
@benjamn updating to 0.11.2 introduced:

```
src/cache/inmemory/entityCache.ts:2:15 - error TS2305:
Module '"apollo-client/node_modules/optimism/lib"' has no exported
member 'OptimisticDependencyFunction'.
```